### ISSUE TITLE
Jest tests fail on v0.2.1

### ISSUE THREAD

**Issue by stovmascript** [lingui/swc-plugin#24]
It seems that #22 introduced something which is throwing off our unit tests. I ran them with `RUST_BACKTRACE=full` if it's any help. Wondering where to look 🤔 Here's the output of one failed test:

```
Errors thrown in src/helpers/prettyBytes.test.js
    ● Test suite failed to run
  
      failed to process failed to invoke plugin: failed to invoke plugin on 'Some("/home/runner/work/monitora-frontend/monitora-frontend/src/helpers/prettyBytes.test.js")'
  
      Caused by:
          0: failed to invoke `/home/runner/work/monitora-frontend/monitora-frontend/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /home/runner/work/monitora-frontend/monitora-frontend/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
          1: RuntimeError: out of bounds memory access
                 at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::h78606889e733645c (<module>[503]:0x6c5ad)
                 at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hbc27da83d658c665 (<module>[70]:0xb7a0)
                 at __transform_plugin_process_impl (<module>[593]:0x7b87f)
                 at __transform_plugin_process_impl.command_export (<module>[1587]:0xfc109)
          2: heap_get_oob
  
      Stack backtrace:
         0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: <unknown>
         5: <unknown>
         6: <unknown>
         7: <unknown>
         8: <unknown>
         9: <unknown>
        10: <unknown>
        11: <unknown>
        12: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
        13: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
        14: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
        15: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  
      Stack backtrace:
         0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
         5: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
         6: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
         7: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  
        at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::h78606889e733645c (<module>[503]:0x6c5ad)
        at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hbc27da83d658c665 (<module>[70]:0xb7a0)
                   at __transform_plugin_process_impl (<module>[593]:0x7b87f)
                   at __transform_plugin_process_impl.command_export (<module>[1[587](https://github.com/monitora-media/monitora-frontend/actions/runs/4253106361/jobs/7397538783#step:6:589)]:0xfc109)
            2: heap_get_oob
        Stack backtrace:
           0: <unknown>
           1: <unknown>
           2: <unknown>
           3: <unknown>
           4: <unknown>
           5: <unknown>
           6: <unknown>
           7: <unknown>
           8: <unknown>
           9: <unknown>
          10: <unknown>
          11: <unknown>
          12: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
          13: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
          14: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
          15: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
        Stack backtrace:
           0: <unknown>
           1: <unknown>
           2: <unknown>
           3: <unknown>
           4: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
           5: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
           6: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
           7: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
        at Object.transformSync (node_modules/src/build/swc/index.ts:357:25)
        at Object.transformSync (node_modules/src/build/swc/index.ts:476:19)
        at Object.process (node_modules/src/build/swc/jest-transformer.ts:74:67)
        at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
        at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
```

**Comment by stovmascript** [comment]
Sorry, it looks like it's not connected to Jest. I get similar errors when trying to build, or run the dev server our Next.js project. I'll try to come back with a better report...

**Comment by thekip** [comment]
Nextjs uses cache, so don't be confused by it. To get cleaner results after switching version remove `.next` folder.
